FROM node:20-alpine
WORKDIR /app
COPY package.json ./

# 替换 apk 的源为阿里云镜像
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/' /etc/apk/repositories

# 配置 npm 使用淘宝镜像（加速依赖下载）
RUN npm config set registry https://registry.npmmirror.com

# 安装 pnpm 和项目依赖
RUN npm install -g pnpm && pnpm install
RUN echo "依赖安装完成..."

# 复制项目文件
COPY . .

# 安装 git
RUN apk add --no-cache git

RUN echo '开始build'
RUN pnpm run docs:build
RUN echo '---build 完成---'

# FROM nginx:stable-alpine

RUN echo '拷贝dist到 nginx目录'
COPY --from=0 /app/docs/.vitepress/dist /usr/share/nginx/html
# COPY --from=0 /app/default.conf /etc/nginx/conf.d/default.conf
